[package]
name = "uni-view"
version = "0.2.5"
authors = ["Li Jinlei <grenlight@icloud.com>"]
edition = "2018"

[dependencies]
libc = "*"
wgpu = { git = "https://github.com/gfx-rs/wgpu-rs", version = "0.6",  rev = "96b70210a87307158da37d0ee8ba69e47318aef8" }
# wgpu = { path = "../../../wgpu-rs" }

lazy_static = "*"
futures = "0.3"

[target.'cfg(target_os = "macos")'.dependencies]
winit = { version = "0.23", features = ["web-sys"] }
raw-window-handle = "0.3"

[target.'cfg(target_os = "ios")'.dependencies]
objc = "*"
objc-foundation = "*"
core-graphics = "*"

[target.'cfg(target_os = "android")'.dependencies]
log = "*"